### ISSUE TITLE
Vichan Reloaded TODO

### ISSUE THREAD

**Issue by CRTrunit** [vichan-reloaded/vichan#4]
This is mostly a TODO list and will take a very long time to complete. I will have to develop the skills required to complete them, so they may never actually be done. Only time will tell.

-  [ ]  Major CSS overhaul. Make it look as much like 4chan as possible.
-  [ ]  Consider redoing JavaScript entirely. If not, make existing scripts match 4chan as much as possible.
-  [ ]  Isolate as much "moderator-adminy" things from the user as possible. Error messages should be as generic as possible whilst not in a debugging mode.  For security and appearance reasons. Not high priority.
- [ ]  Introduce new caching methods; PHP 5 will hit EOL very soon and with it APC. 
-  [ ] Bug fixing / stability improvements
- [ ] Implement warnings.
- [ ] Moderator overhaul: Ban Requests for janitors, and a catalog displaying reports from all boards. Idea: Maybe a JSON stream of reports fed into something like: https://github.com/desuwa/fourcat ? Big bonus points if we can implement moderation on said catalog. This is a lot of work I imagine, but I also think it will be very useful in communities where moderation needs to scale. I'd also like to take some of the deletion utilities that were recently implemented in OpenIB and bring them to vichan, but I do not want to make this fork a frakenstine's monster from various vichan forks. I could do that by mix mashing NPFchan, HokkaChan, and Lainchan together.

To be expanded when appropriate.
